// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Mpujcd4D1Gp6vVcXTf1x66wfWkZUV90',
    appId: '1:1009812509944:web:7dc419796cca02b4df570d',
    messagingSenderId: '1009812509944',
    projectId: 'videocall-d880d',
    authDomain: 'videocall-d880d.firebaseapp.com',
    storageBucket: 'videocall-d880d.appspot.com',
    measurementId: 'G-GRKC0YVYDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnktlewHsfxssOYKgfqech64VGWpm_6Y',
    appId: '1:1009812509944:android:d19f9dde41427c24df570d',
    messagingSenderId: '1009812509944',
    projectId: 'videocall-d880d',
    storageBucket: 'videocall-d880d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNDZWLrAlxzgNngYipV5X1foc0Nsz9Wc',
    appId: '1:1009812509944:ios:791a40e9d34f985cdf570d',
    messagingSenderId: '1009812509944',
    projectId: 'videocall-d880d',
    storageBucket: 'videocall-d880d.appspot.com',
    iosClientId: '1009812509944-i8cku9t6usi88lcn8f9jhbgc2522635l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
